spring:
  datasource:
    hikari:
      minimum-idle: 1
  profiles:
    active: dev,discovery-dev
  application:
    name: wuyan-admin





#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mappings/**/*Mapper.xml
  global-config:
    # 数据库相关配置
    db-config:
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
