spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-m5e90k929g572chi5fo.mysql.rds.aliyuncs.com:3306/mysys?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: my_system
    password: Wgg1940845501!
    hikari:
      minimum-idle: 1


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mappings/**/*Mapper.xml
  global-config:
    # 数据库相关配置
    db-config:
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1